import type { AlgorithmTool } from '../types'

export const ALGORITHM_TOOLS: AlgorithmTool[] = [
  // 基础控制
  {
    id: 'no_response',
    name: '用户无应答处理',
    description: '当用户本轮无应答时，将空内容替换为指定文字，让大模型感知到沉默',
    fullDescription: '当用户本轮什么都没说时，系统会把空内容替换成你指定的文字。选用后提示词顶部注入 `# 用户无应答：用户无应答`，可在正文中引用这个状态做相应处理。',
    category: '基础控制',
    usageTemplate: '# 用户无应答：用户无应答',
    excludeCapabilities: ['用户无应答处理', '沉默检测', '无应答兜底'],
  },
  {
    id: 'end_condition',
    name: '任务结束条件',
    description: '定义任务完成的判断条件，系统据此触发结束流程',
    fullDescription: '告诉系统"什么情况下这个任务算完成了"。选用后提示词顶部注入 `# 任务结束条件: ` 模板行，需要补充具体条件，如"用户已确认预约时间"。',
    category: '基础控制',
    usageTemplate: '# 任务结束条件: ',
    excludeCapabilities: ['任务结束判断', '流程终止条件'],
  },
  {
    id: 'collect_jump',
    name: '信息采集跳转',
    description: '采集到指定信息后自动跳转下一节点，支持格式校验',
    fullDescription: '当某个实体（如手机号、邮箱）被成功采集后，当前节点自动结束并跳转下一节点。第三个字段为可选校验规则：手机号、邮箱，不填则不校验。',
    category: '基础控制',
    usageTemplate: '# 开启信息采集跳转下一个节点$$实体名$$手机号',
    excludeCapabilities: ['信息采集跳转', '节点自动跳转'],
  },
  {
    id: 'end_after_reply',
    name: '用户回复后结束',
    description: '本轮输出后等用户回复，再结束流程',
    fullDescription: '开启后，系统会在本轮输出完成、等到用户回复后才触发结束流程，而不是立即结束。适合需要确认用户收到信息的场景。',
    category: '基础控制',
    usageTemplate: '# 用户回复后结束流程',
    excludeCapabilities: ['流程结束时机控制'],
  },

  // 知识库与检索
  {
    id: 'rag',
    name: '知识库检索 RAG',
    description: '指定本轮优先从哪些知识文档中检索，多个文档用空格或逗号分隔',
    fullDescription: '告诉系统这一轮检索时优先从哪几个文档里找。选用后提示词顶部注入 `# @RAG 文档: ` 模板行，需要补充具体文档名，如 `# @RAG 文档: 售后FAQ 退款政策`。',
    category: '知识库与检索',
    usageTemplate: '# @RAG 文档: ',
    excludeCapabilities: ['知识库查询', 'FAQ检索', '文档检索'],
  },
  {
    id: 'knowledge_query',
    name: '额外知识文档查询',
    description: '在正常检索之外，额外指定检索任务，支持过滤字段和候选选项',
    fullDescription: '在正常检索之外额外加一个检索任务。支持指定过滤字段和候选选项，如 `# 知识文档查询: ; 过滤字段: brand; 选项: 比亚迪, 吉利`。',
    category: '知识库与检索',
    usageTemplate: '# 知识文档查询: ',
    excludeCapabilities: ['额外知识检索', '品牌文档查询'],
  },
  {
    id: 'doc_candidate_reply',
    name: '文档知识候选回复',
    description: '知识库中存储了候选回复时，系统按轮询选一个',
    fullDescription: '开启后，如果知识库里存了候选回复，系统会按轮询逻辑选其中一个作为回复。适合知识库内容已包含多版本话术的场景。',
    category: '知识库与检索',
    usageTemplate: '# 开启文档知识候选回复',
    excludeCapabilities: ['知识库候选回复'],
  },

  // 时间处理
  {
    id: 'time_extract',
    name: '时间抽取',
    description: '从用户话语中提取时间表达，转为结构化 ISO 格式存入变量',
    fullDescription: '从当前用户说的话里提取时间表达，输出成结构化时间格式，存进变量 `ISO期望预约时间`。后续可用 `@{ISO期望预约时间}` 引用，或配合口语时间推荐工具做二次转换。',
    category: '时间处理',
    usageTemplate: '# @act: 日期时间解析 -> ISO期望预约时间',
    excludeCapabilities: ['时间识别', '预约时间提取', '日期解析'],
  },
  {
    id: 'oral_time',
    name: '口语时间推荐',
    description: '从候选时间列表中挑最接近用户期望的几个，转成口语表达',
    fullDescription: '从候选可预约时间里挑最接近客户期望时间的最多3个，转成口语表达，可直接嵌进话术。需配合时间抽取工具一起使用，结果用 `#{推荐口语时间}` 引用。',
    category: '时间处理',
    usageTemplate: '# @赋值: 口语日期时间(日期时间=${可预约时间列表}, 目标时间=@act: 日期时间解析) -> 推荐口语时间',
    excludeCapabilities: ['口语时间转换', '可预约时间推荐'],
  },
  {
    id: 'after_school_time',
    name: '课外时间筛选',
    description: '从时间段 JSON 中筛选晚间/课外可用时段，支持同时输出口语版本',
    fullDescription: '从一份时间段 JSON 里自动筛选出晚间/课外时段。加 `口语` 参数可同时输出结构化时间和口语时间两个变量，分别用 `@{ISO可预约时间}` 和 `@{口语可预约时间}` 引用。',
    category: '时间处理',
    usageTemplate: '# @赋值: 课外时间(日期时间=${可预约时间段}, 口语) -> ISO可预约时间, 口语可预约时间',
    excludeCapabilities: ['课外时间筛选', '晚间时段提取'],
  },
  {
    id: 'deadline_oral',
    name: '口语截止日期',
    description: '根据来访日期加天数周期，算出截止日期并转成口语表达',
    fullDescription: '根据来访日期加上天数周期，算出相对今天的截止日期，并转成口语表达。结果用 `#{推荐复查日期}` 引用，可直接嵌进话术。',
    category: '时间处理',
    usageTemplate: '# @赋值: 口语截止日期(开始日期=${来访日期}, 周期=7) -> 推荐复查日期',
    excludeCapabilities: ['截止日期计算', '复查日期推荐'],
  },
  {
    id: 'time_extract_legacy',
    name: '开启时间抽取（旧版）',
    description: '旧版时间抽取开关，抽取结果以额外信息方式追加到 system',
    fullDescription: '旧版时间抽取开关。抽取到的口语化时间结果会以"额外信息"方式直接追加到 system。新提示词建议优先使用 `# @act: 日期时间解析` 配合 `# @赋值` 写法。',
    category: '时间处理',
    usageTemplate: '# 开启时间抽取',
    excludeCapabilities: ['时间识别'],
  },
  {
    id: 'oral_date',
    name: '口语日期',
    description: '把结构化日期转成口语表达，结果存入变量',
    fullDescription: '把结构化日期（如 ${来访日期}）转成口语表达，存入指定变量。结果用 `#{口语化来访日期}` 引用。示例：`# @赋值: 口语日期(日期=${来访日期}) -> 口语化来访日期`',
    category: '时间处理',
    usageTemplate: '# @赋值: 口语日期(日期=${来访日期}) -> 口语化来访日期',
    excludeCapabilities: ['日期口语化'],
  },
  {
    id: 'oral_time_only',
    name: '口语时间',
    description: '把结构化时间转成口语表达，结果存入变量',
    fullDescription: '把结构化时间（如 ${预约时间}）转成口语表达，存入指定变量。结果用 `#{口语化预约时间}` 引用。示例：`# @赋值: 口语时间(时间=${预约时间}) -> 口语化预约时间`',
    category: '时间处理',
    usageTemplate: '# @赋值: 口语时间(时间=${预约时间}) -> 口语化预约时间',
    excludeCapabilities: ['时间口语化'],
  },
  {
    id: 'oral_datetime_no_target',
    name: '口语日期时间（无目标时间）',
    description: '把多个结构化日期时间转成口语表达，支持指定预选数量',
    fullDescription: '把一个或多个结构化日期时间转成口语化表述，支持 `预选数量` 参数（默认最多3个）。无需指定目标时间，适合直接展示可预约时间列表。结果用 `#{口语可预约时间}` 引用。',
    category: '时间处理',
    usageTemplate: '# @赋值: 口语日期时间(日期时间=${可预约时间}, 预选数量=2) -> 口语可预约时间',
    excludeCapabilities: ['口语时间转换'],
  },

  // 地址与意图
  {
    id: 'address',
    name: '地址补全',
    description: '自动从对话中提取用户地址，支持省市区三级联动',
    fullDescription: '开启后系统自动从对话中提取用户地址信息，支持省市区三级联动。选用后无需在提示词正文中描述地址采集逻辑，由工具接管。',
    category: '地址与意图',
    usageTemplate: '# 开启地址补全',
    excludeCapabilities: ['地址采集', '省市区提取', '收货地址解析'],
  },
  {
    id: 'address_off',
    name: '关闭地址补全',
    description: '即使自动条件满足，也强制关闭地址抽取',
    fullDescription: '即使动态变量中定义了省/市/区等字段（可能触发自动地址抽取），也强制不做地址抽取。适合某些节点不需要地址逻辑的场景。',
    category: '地址与意图',
    usageTemplate: '# 关闭地址补全',
    excludeCapabilities: [],
  },
  {
    id: 'address_auto',
    name: '汽车行业地址匹配',
    description: '在地址抽取之后，进一步匹配到汽车门店/经销商',
    fullDescription: '在地址抽取完成后，进一步将地址匹配到最近的汽车门店或经销商。需同时开启地址补全，工具会自动接管门店匹配逻辑。',
    category: '地址与意图',
    usageTemplate: '# 开启地址补全\n# 开启汽车行业地址匹配：用户所在地',
    excludeCapabilities: ['地址采集', '门店匹配', '经销商定位'],
  },
  {
    id: 'nlu',
    name: '意图筛选 NLU',
    description: '识别用户意图，只将命中的分支保留进提示词，减少大模型干扰',
    fullDescription: '把若干候选分支交给意图识别服务，系统判断当前用户话语命中哪个分支，只把命中的那部分保留进提示词。在正文中用 `<NLU>...</NLU>` 块配置意图分支，每行格式：`- 如果客户...，$$回复内容`。',
    category: '地址与意图',
    usageTemplate: '',
    excludeCapabilities: ['意图识别', '分支判断'],
  },
  {
    id: 'asr_fix',
    name: '车型识别纠错',
    description: '自动纠正语音识别把品牌、车系、车型名识别错的情况',
    fullDescription: '自动纠正 ASR 把品牌/车系/车型名识别错的情况。加 `+拼音` 参数，纠错失败时还会额外尝试用拼音再匹配一遍：`# 开启车型识别纠错+拼音`',
    category: '地址与意图',
    usageTemplate: '# 开启车型识别纠错',
    excludeCapabilities: ['车型名称纠错', 'ASR纠错', '品牌识别纠正'],
  },

  // 承接词
  {
    id: 'connector_on',
    name: '开启承接词',
    description: '在 Bot 全局没开承接词时，强制为当前流程开启承接词',
    fullDescription: '大模型开始思考时先播出过渡语（如"好的"、"稍等"），让通话不显得太沉默。在 Bot 全局没开承接词时，此命令强制为当前流程开启。',
    category: '承接词',
    usageTemplate: '# 开启承接词',
    excludeCapabilities: ['承接词', '过渡语', '等待提示'],
  },
  {
    id: 'connector_off',
    name: '关闭承接词',
    description: '在 Bot 全局已开承接词时，强制为当前流程关闭承接词',
    fullDescription: '在 Bot 全局已开承接词的情况下，强制为当前流程关闭，不播放任何过渡语。',
    category: '承接词',
    usageTemplate: '# 关闭承接词',
    excludeCapabilities: [],
  },
  {
    id: 'connector_generative',
    name: '生成式承接词',
    description: '不走分类式承接词，让模型按当前上下文生成承接词',
    fullDescription: '不再走预设的分类式承接词库，而是让模型根据当前对话上下文自动生成更自然的承接词。通常与"开启承接词"配合使用。',
    category: '承接词',
    usageTemplate: '# 使用生成式承接词',
    excludeCapabilities: [],
  },
  {
    id: 'connector_replace',
    name: '承接词替换',
    description: '把某个承接词替换成另一个，可以连续写多条',
    fullDescription: '把系统可能播放的某个承接词替换成另一个更合适的表达。可以连续写多条。示例：`# @承接词.替换: 稍等一下 -> 我帮您看一下`',
    category: '承接词',
    usageTemplate: '# @承接词.替换: 您稍等 -> 我帮您确认一下',
    excludeCapabilities: [],
  },
  {
    id: 'connector_delay',
    name: '承接词延迟',
    description: '指定承接词的输出延迟秒数，最小约 0.5s',
    fullDescription: '指定承接词的输出延迟秒数。代码里会限制最小约 0.5s，太小或太大都会被纠正。示例：`# @承接词.延迟: 0.6s`',
    category: '承接词',
    usageTemplate: '# @承接词.延迟: 0.6s',
    excludeCapabilities: [],
  },
  {
    id: 'connector_no_reply',
    name: '承接词不参与回复生成',
    description: '承接词仍可提前播报，但不把承接词追加进最终生成 messages',
    fullDescription: '承接词仍可提前播报给用户，但不会把承接词内容追加进最终生成的 messages，避免影响大模型的正式回复内容。',
    category: '承接词',
    usageTemplate: '# 承接词不参与回复生成',
    excludeCapabilities: [],
  },
  // 话术控制
  {
    id: 'options_rotate',
    name: '候选话术轮换',
    description: '根据整数变量（如拒绝次数）自动选择不同话术版本',
    fullDescription: '根据某个整数变量（如拒绝次数）的当前值，自动选择不同的话术。在正文中用 `<options: 变量名>` 占位，再在下方写 `<options>...</options>` 配置不同值对应的话术。',
    category: '话术控制',
    usageTemplate: '',
    excludeCapabilities: ['话术轮换', '拒绝次数话术切换'],
  },
  {
    id: 'candidate_reply',
    name: '候选回复轮换',
    description: '定义多个可互换的话术版本，同一通话内按轮换逻辑选其中一个',
    fullDescription: '定义多个可以互换的话术版本，系统会按轮换逻辑选其中一个，同一通话中不会反复变化。在正文中用 `《候选回复》...《/候选回复》` 块配置，每行格式：`占位词 - "候选1" - "候选2"`。',
    category: '话术控制',
    usageTemplate: '',
    excludeCapabilities: ['候选回复', '话术多样化'],
  },
  {
    id: 'random_pick',
    name: '随机选取话术',
    description: '从多句话里随机抽 N 句放进提示词，同一通话内抽样结果不变',
    fullDescription: '从写好的多句话里随机选 N 句放进提示词，同一通话内抽样结果不变，避免话术在同一通话里来回跳。在正文中用 `<随机选取，N>...</随机选取>` 块配置。',
    category: '话术控制',
    usageTemplate: '',
    excludeCapabilities: ['随机话术选取'],
  },
  {
    id: 'no_emotion',
    name: '禁止情绪话术',
    description: '禁止输出"太好了""太棒了"等情绪化口头禅',
    fullDescription: '开启后，大模型不会输出"太好了""太棒了"等情绪化口头禅，使回复更专业克制。',
    category: '话术控制',
    usageTemplate: '# 禁止输出情绪话术',
    excludeCapabilities: ['情绪化表达', '情绪口头禅'],
  },
  {
    id: 'no_repeat',
    name: '禁止整句重复',
    description: '不允许完整复述历史回复，必须改写',
    fullDescription: '开启后，大模型不允许完整复述历史回复中的句子，必须改写表达，避免回复单调重复。',
    category: '话术控制',
    usageTemplate: '# 禁止整句重复',
    excludeCapabilities: ['重复话术检测'],
  },

  // 数据处理
  {
    id: 'phone_segment',
    name: '号码分段',
    description: '把手机号/订单号按4位分段，方便口播，支持转中文数字',
    fullDescription: '把长数字（手机号、订单号等）按4位分组，避免大模型一气儿念出来。加 `中文` 参数会把数字换成中文数字。结果用 `#{分段号码}` 引用。',
    category: '数据处理',
    usageTemplate: '# @赋值: 号码分段(${手机号}) -> 分段号码',
    excludeCapabilities: ['号码分段播报', '电话号码口播'],
  },
  {
    id: 'phone_last4',
    name: '号码后四位',
    description: '提取号码后四位，支持转中文数字',
    fullDescription: '提取号码的后四位，加 `中文` 参数转成中文数字。结果用 `#{号码尾号}` 引用，适合核实身份场景。',
    category: '数据处理',
    usageTemplate: '# @赋值: 号码后四位(${手机号}) -> 号码尾号',
    excludeCapabilities: ['号码后四位提取'],
  },
  {
    id: 'oral_amount',
    name: '口语金额/数量',
    description: '将各种格式的金额或数量转成大模型可自然念出来的中文表达',
    fullDescription: '自动处理各种格式的金额或数量（如 ¥595.00元、8,179元），转成大模型可以自然念出来的中文表达。加 `去单位` 参数会去掉单位。结果用 `#{口语金额}` 引用。',
    category: '数据处理',
    usageTemplate: '# @赋值: 口语数量(${金额}) -> 口语金额',
    excludeCapabilities: ['金额口语化', '数量口播转换'],
  },
  {
    id: 'calc',
    name: '开启计算',
    description: '客户问总价、优惠价等时，先调用计算工具算出结果再回复',
    fullDescription: '开启后，当客户问到总价、优惠后价格、差价之类的问题时，系统会先让模型生成算式并调用计算工具，再把结果填进回复里。结果存在 `计算任务` 变量里，用 `@{计算任务}` 引用。',
    category: '数据处理',
    usageTemplate: '# 开启计算',
    excludeCapabilities: ['价格计算', '数学运算', '差价计算'],
  },
  {
    id: 'assign_direct',
    name: '直接赋值',
    description: '把某个变量的值原样赋给另一个动态变量',
    fullDescription: '把某个值原样赋给另一个动态变量，适合做变量别名或中间转存。示例：`# @赋值: 直接赋值(${客户备注}) -> 当前备注摘要`',
    category: '数据处理',
    usageTemplate: '# @赋值: 直接赋值(${客户备注}) -> 当前备注摘要',
    excludeCapabilities: [],
  },
  {
    id: 'replace_var',
    name: '@替换',
    description: '把 system 中某个旧字符串替换成指定变量当前值',
    fullDescription: '把 system 中某个旧字符串替换成指定变量当前值。常与 `# @赋值: 口语日期` 配合使用，先赋值再替换。示例：`# @替换(old=${来访日期}, new=口语化来访日期)`',
    category: '数据处理',
    usageTemplate: '# @替换(old=${来访日期}, new=口语化来访日期)',
    excludeCapabilities: [],
  },
  {
    id: 'custom_variable',
    name: '自定义变量',
    description: '在第一轮对话时初始化一组动态变量，适合外部传入字段的别名映射',
    fullDescription: '在第一轮对话时初始化一组动态变量。常用于把外部传入但未直接映射到动态变量表的字段，转成话术里可引用的变量。如果重复定义多个块，当前实现会使用最后一个。',
    category: '数据处理',
    usageTemplate: '<自定义变量>\n变量名1：变量值1\n变量名2：变量值2\n</自定义变量>',
    excludeCapabilities: [],
  },
  {
    id: 'assign_wandou_chess',
    name: '豌豆围棋约课',
    description: '把可约课次表拆成"原老师课程安排"和"其他老师课程安排"两类',
    fullDescription: '针对豌豆围棋约课场景，把可约课次表拆成"原老师课程安排"和"其他老师课程安排"两类，分别存入对应变量。示例：`# @赋值: 豌豆围棋约课(可约课次=${可约课次表}) -> 原老师课程安排，其他老师课程安排`',
    category: '数据处理',
    usageTemplate: '# @赋值: 豌豆围棋约课(可约课次=${可约课次表}) -> 原老师课程安排，其他老师课程安排',
    excludeCapabilities: [],
  },
  {
    id: 'assign_dealer',
    name: '候选经销商',
    description: '把候选经销商 JSON 列表转成一行可读名称串',
    fullDescription: '把候选经销商 JSON 列表转成一行可读名称串，方便直接嵌入话术。示例：`# @赋值: 候选经销商([{"name": "杭州A店"}]) -> 候选经销商名称`，输出效果类似：杭州A店、杭州B店。',
    category: '数据处理',
    usageTemplate: '# @赋值: 候选经销商([{"name": "门店A"}]) -> 候选经销商名称',
    excludeCapabilities: [],
  },

  // 增强能力
  {
    id: 'deep_think',
    name: '开启深度思考',
    description: '调用上一轮的推理结果，增强当前回复质量',
    fullDescription: '开启后，系统会尝试调用上一轮的推理结果，增强当前回复的质量和连贯性。适合需要多轮推理的复杂场景。',
    category: '增强能力',
    usageTemplate: '# 开启深度思考',
    excludeCapabilities: ['深度推理', '多轮推理增强'],
  },
  {
    id: 'instruction_enhance',
    name: '开启指令增强',
    description: '更严格地执行系统指令，适合复杂提示词',
    fullDescription: '开启后，系统会更严格地执行提示词中的指令，适合包含复杂逻辑或多条约束的提示词场景。',
    category: '增强能力',
    usageTemplate: '# 开启指令增强',
    excludeCapabilities: ['指令遵从增强'],
  },
  {
    id: 'parallel_extract',
    name: '并行抽取实体',
    description: '多个实体同时抽取，速度更快（系统默认行为，显式声明可提高可读性）',
    fullDescription: '开启后，提示词中定义的多个实体会同时并行抽取，速度更快。这是系统默认行为，显式声明可提高可读性。',
    category: '增强能力',
    usageTemplate: '# 并行抽取实体',
    excludeCapabilities: ['实体并行抽取'],
  },
  {
    id: 'serial_extract',
    name: '串行抽取实体',
    description: '多个实体按顺序逐一抽取，适合有依赖关系的实体',
    fullDescription: '开启后，提示词中定义的多个实体会按顺序逐一抽取，而不是并行。适合实体之间有依赖关系的场景。',
    category: '增强能力',
    usageTemplate: '# 串行抽取实体',
    excludeCapabilities: [],
  },
  {
    id: 'condition_block',
    name: '条件块',
    description: '根据变量值动态切换话术段落，未命中的分支大模型完全看不到',
    fullDescription: '把同一位置的话术写成多个版本，系统根据变量当前值自动选择哪个版本交给大模型。支持 `<条件 默认>`、`<条件 字符串变量=[变量名] 表达式=\'...\'>`、`<条件 整数变量=[变量名] 表达式=\'...\'>`。注意：不要把必须执行的命令放在条件块里。',
    category: '增强能力',
    usageTemplate: '',
    excludeCapabilities: ['条件分支话术', '动态话术切换'],
  },
  {
    id: 'stage_mapping',
    name: '阶段变量映射',
    description: '定义每个阶段需要哪些变量，系统自动判断当前应推进到哪个阶段',
    fullDescription: '定义每个阶段需要哪些变量，系统会自动判断"哪些变量已有值、哪些还没有"，动态告知大模型当前应推进到哪个阶段。在正文中用 `# 阶段和变量映射关系` 块配置，再用 `get_next("首轮破冰")` 引用当前阶段。',
    category: '增强能力',
    usageTemplate: '',
    excludeCapabilities: ['阶段自动推进', '多阶段流程管理'],
  },

  // 流程控制
  {
    id: 'ignore_question_mark',
    name: '忽略问号后输出',
    description: '流式输出时，遇到问号后可截断后续内容',
    fullDescription: '流式输出时，遇到问号后可截断后续内容，避免大模型在问句后继续输出多余内容。',
    category: '流程控制',
    usageTemplate: '# 忽略问号后输出',
    excludeCapabilities: [],
  },
  {
    id: 'block_end_on_question',
    name: '出现问句时不允许流程结束',
    description: '如果回复里出现问句，则取消 finish 结束',
    fullDescription: '如果大模型的回复里出现问句，则取消 `finish` 结束动作，确保对话继续进行，不会在还有问题未解答时就结束流程。',
    category: '流程控制',
    usageTemplate: '# 出现问句时不允许流程结束',
    excludeCapabilities: [],
  },
  {
    id: 'ignore_finish',
    name: '忽略句末 finish',
    description: '遇到文本里的句末 finish 结束符时，不自动转成结束工具调用',
    fullDescription: '遇到文本里的句末 `finish` 结束符时，不自动转成结束工具调用。适合提示词正文中包含"finish"字样但不希望触发结束的场景。',
    category: '流程控制',
    usageTemplate: '# 忽略句末 finish',
    excludeCapabilities: [],
  },
  {
    id: 'disable_set_variable',
    name: '禁止输出 set_variable 工具',
    description: '提示模型不要调用 set_variable 工具',
    fullDescription: '提示模型不要调用 `set_variable` 工具，适合某些节点不需要变量赋值操作的场景。',
    category: '流程控制',
    usageTemplate: '# 禁止输出 set_variable 工具',
    excludeCapabilities: [],
  },
  {
    id: 'focus_subtask',
    name: '专注当前子任务',
    description: '当前子任务已确定时，移除其他子任务说明，只保留当前子任务上下文',
    fullDescription: '当前子任务已确定时，移除其他子任务说明，只保留当前子任务上下文，减少大模型的干扰信息，提升指令遵从度。',
    category: '流程控制',
    usageTemplate: '# 专注当前子任务',
    excludeCapabilities: [],
  },
]

export const TOOL_CATEGORIES = [
  '基础控制',
  '知识库与检索',
  '时间处理',
  '地址与意图',
  '承接词',
  '话术控制',
  '数据处理',
  '增强能力',
  '流程控制',
]
